name: Test

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  test:
    name: Smoke test
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Smoke test
        run: ./test/smoke.sh
